import { State, Evidence } from "./domain";

export const DEMO_DATE = "2026-09-30";

export function demoState(): State {
  const d = DEMO_DATE;
  const proof: Evidence = {
    name: "bukti-simulasi.txt",
    type: "text/plain",
    data: "data:text/plain;base64,RGF0YSBzaW11bGFzaSBidWFoYWhhLiBCdWthbiBidWt0aSB0cmFuc2Frc2kgbnlhdGEu",
  };
  return {
    version: 1,
    products: [
      {
        id: "p1",
        name: "Jeruk Medan",
        sku: "BH-JRK-001",
        unit: "kg",
        cost: 18000,
        price: 25000,
        stock: 185,
        low: 30,
        color: "orange",
      },
      {
        id: "p2",
        name: "Apel Fuji",
        sku: "BH-APL-002",
        unit: "kg",
        cost: 32000,
        price: 45000,
        stock: 82,
        low: 20,
        color: "red",
      },
      {
        id: "p3",
        name: "Pisang Cavendish",
        sku: "BH-PSG-003",
        unit: "kg",
        cost: 14000,
        price: 22000,
        stock: 64,
        low: 25,
        color: "yellow",
      },
      {
        id: "p4",
        name: "Mangga Harum Manis",
        sku: "BH-MGG-004",
        unit: "kg",
        cost: 22000,
        price: 35000,
        stock: 18,
        low: 25,
        color: "green",
      },
      {
        id: "p5",
        name: "Anggur Red Globe",
        sku: "BH-AGR-005",
        unit: "kg",
        cost: 48000,
        price: 65000,
        stock: 12,
        low: 15,
        color: "purple",
      },
      {
        id: "p6",
        name: "Semangka Merah",
        sku: "BH-SMG-006",
        unit: "buah",
        cost: 28000,
        price: 42000,
        stock: 45,
        low: 10,
        color: "green",
      },
    ],
    customers: [
      {
        id: "c1",
        name: "Toko Buah Segar",
        phone: "081234567890",
        address: "Jl. Pasar Minggu No. 24, Jakarta Selatan",
        note: "Pengiriman pagi sebelum pukul 10.00.",
      },
      {
        id: "c2",
        name: "Dapur Ibu Rani",
        phone: "081298765432",
        address: "Jl. Kemang Raya No. 18, Jakarta Selatan",
        note: "Hubungi penerima sebelum tiba.",
      },
      {
        id: "c3",
        name: "Kedai Jus Pagi",
        phone: "085712345678",
        address: "Jl. Tebet Barat No. 7, Jakarta Selatan",
        note: "",
      },
      {
        id: "c4",
        name: "Hotel Taman Kota",
        phone: "081388990011",
        address: "Jl. Gatot Subroto No. 32, Jakarta Selatan",
        note: "Masuk melalui pintu loading.",
      },
      {
        id: "c5",
        name: "Warung Bu Siti",
        phone: "082112340098",
        address: "Jl. Pejaten Barat No. 11, Jakarta Selatan",
        note: "",
      },
    ],
    orders: [
      {
        id: "PSN-1001",
        customerId: "c1",
        date: d,
        completedAt: d,
        items: [
          { productId: "p1", qty: 50, price: 25000, cost: 18000 },
          { productId: "p2", qty: 20, price: 45000, cost: 32000 },
        ],
        discount: 0,
        note: "Kirim pagi",
        status: "selesai",
      },
      {
        id: "PSN-1002",
        customerId: "c4",
        date: d,
        completedAt: d,
        items: [
          { productId: "p2", qty: 30, price: 45000, cost: 32000 },
          { productId: "p5", qty: 10, price: 65000, cost: 48000 },
        ],
        discount: 50000,
        note: "Pintu loading",
        status: "selesai",
      },
      {
        id: "PSN-1003",
        customerId: "c3",
        date: d,
        items: [
          { productId: "p1", qty: 25, price: 25000, cost: 18000 },
          { productId: "p3", qty: 15, price: 22000, cost: 14000 },
        ],
        discount: 0,
        note: "",
        status: "dikirim",
      },
      {
        id: "PSN-1004",
        customerId: "c2",
        date: d,
        items: [
          { productId: "p2", qty: 10, price: 45000, cost: 32000 },
          { productId: "p4", qty: 8, price: 35000, cost: 22000 },
        ],
        discount: 0,
        note: "Hubungi Ibu Rani",
        status: "disiapkan",
      },
      {
        id: "PSN-1005",
        customerId: "c5",
        date: d,
        items: [{ productId: "p1", qty: 20, price: 25000, cost: 18000 }],
        discount: 0,
        note: "",
        status: "dikonfirmasi",
      },
      {
        id: "PSN-1006",
        customerId: "c1",
        date: d,
        items: [{ productId: "p6", qty: 12, price: 42000, cost: 28000 }],
        discount: 0,
        note: "Pesanan tambahan",
        status: "baru",
      },
    ],
    payments: [
      {
        id: "BYR-001",
        orderId: "PSN-1001",
        date: d,
        amount: 2150000,
        method: "Transfer",
        verified: true,
        deposited: 0,
        proof,
      },
      {
        id: "BYR-002",
        orderId: "PSN-1002",
        date: d,
        amount: 1950000,
        method: "COD",
        verified: true,
        deposited: 1500000,
      },
      {
        id: "BYR-003",
        orderId: "PSN-1004",
        date: d,
        amount: 730000,
        method: "Transfer",
        verified: false,
        deposited: 0,
        proof,
      },
    ],
    trips: [
      {
        id: "JLN-001",
        orderIds: ["PSN-1001", "PSN-1002"],
        date: d,
        driver: "Pak Dedi",
        vehicle: "B 9241 SFG",
        address: "Pasar Minggu · Gatot Subroto",
        note: "Rute pagi",
        status: "Terkirim",
      },
      {
        id: "JLN-002",
        orderIds: ["PSN-1003"],
        date: d,
        driver: "Pak Agus",
        vehicle: "B 9128 TJK",
        address: "Tebet Barat",
        note: "",
        status: "Dalam perjalanan",
      },
    ],
    expenses: [
      {
        id: "BIA-001",
        date: d,
        category: "Bensin",
        amount: 100000,
        person: "Pak Dedi",
        tripId: "JLN-001",
        vehicle: "B 9241 SFG",
        note: "Isi bensin rute pagi",
      },
      {
        id: "BIA-002",
        date: d,
        category: "Bensin",
        amount: 75000,
        person: "Pak Agus",
        tripId: "JLN-002",
        vehicle: "B 9128 TJK",
        note: "Rute Tebet",
      },
      {
        id: "BIA-003",
        date: d,
        category: "Operasional",
        amount: 50000,
        person: "Owner",
        tripId: "",
        vehicle: "",
        note: "Kemasan dan kantong",
      },
    ],
    returns: [
      {
        id: "RTR-001",
        orderId: "PSN-1001",
        productId: "p1",
        qty: 2,
        reason: "Kulit buah rusak saat diterima",
        date: d,
        status: "Diajukan",
        condition: "Rusak",
        refund: 50000,
        proof,
      },
    ],
    movements: [
      ...[
        { id: "p1", qty: 260 },
        { id: "p2", qty: 132 },
        { id: "p3", qty: 79 },
        { id: "p4", qty: 20 },
        { id: "p5", qty: 22 },
        { id: "p6", qty: 45 },
      ].map((p, n) => ({
        id: `MUT-A${n}`,
        date: d,
        productId: p.id,
        qty: p.qty,
        type: "Masuk" as const,
        note: "Saldo awal simulasi",
        loss: 0,
      })),
      ...[
        { p: "p1", qty: 50, o: "PSN-1001" },
        { p: "p2", qty: 20, o: "PSN-1001" },
        { p: "p2", qty: 30, o: "PSN-1002" },
        { p: "p5", qty: 10, o: "PSN-1002" },
        { p: "p1", qty: 25, o: "PSN-1003" },
        { p: "p3", qty: 15, o: "PSN-1003" },
      ].map((m, n) => ({
        id: `MUT-K${n}`,
        date: d,
        productId: m.p,
        qty: m.qty,
        type: "Keluar" as const,
        note: m.o,
        loss: 0,
      })),
      {
        id: "MUT-R1",
        date: d,
        productId: "p4",
        qty: 2,
        type: "Rusak",
        note: "Buah terlalu matang",
        loss: 44000,
      },
    ],
  };
}
